<div id="left_block">
    <div class="block_r ser content_blocks">
        <h3><b>Управление сайтом</b></h3>  
        <ul>
            <li><a href="/pages/<?=$this->layout()->lang ?>/admin_pages/">Структура</a></li>
            <li><a href="/blocks/<?=$this->layout()->lang ?>/admin_blocks/">Блоки</a></li>            
            <li><a href="/users/<?=$this->layout()->lang ?>/admin_users/">Пользователи сайта</a></li>
            
        </ul>
    </div>
     <div class="block_r orange content_blocks">
        <h3><b>Каталог товаров</b></h3>
       <!--  <p class="info_block">Ниже указаны действия</p> -->
        <ul>
          <li><a href="/catalog/<?=$this->layout()->lang ?>/admin_division/">Разделы каталога</a></li>
          <li><a href="/catalog/<?=$this->layout()->lang ?>/admin_product_options/">Список Параметров</a></li>         
        </ul>
        </div>
</div>

<div id="right_block">

      <div class="block_r blue">
        <h3><b>Дополнительно</b></h3>

        <ul>
            <li  ><a href="/constructor/<?=$this->layout()->lang ?>/admin_types/">Конструктор блюд</a></li>
         <li  ><a href="/blocks/<?=$this->layout()->lang ?>/admin_blocks/">Блоки</a></li>

           <li  ><a href="/admin/<?=$this->layout()->lang ?>/divtype/">Типы разделов</a></li>
           <li  ><a href="/feedbacktemplates/<?=$this->layout()->lang ?>/admin_feedbacktemplates/">Шаблоны писем</a></li>
           <li  ><a href="/orders/<?=$this->layout()->lang ?>/admin_orders/">Заказы</a></li>
          <!-- <li ><a href="/newsletter/<?=$this->layout()->lang ?>/admin_newsletter/">Рассылка</a></li>
	        <li  ><a href="/newsletter/<?=$this->layout()->lang ?>/admin_boxes/">Подписчики</a></li> -->
        </ul>
      </div>
    </div>
