<div id="left_block">
<?php $groupe = ''; ?>  
<?php foreach ($this->modules as $module){ ?>

    <?php if ($groupe != $module->groupe_name){ ?>
    
    	<?php if ($groupe!=''){?>
    		</div>
    		<div class="block_r orange content_blocks"> 
    	<?php } else {?>
    		<div class="block_r orange content_blocks"> 
    	<?php }?>
    	
    	<?php if ($module->module_link == null) { ?>
            	<?php $link = '/'.$module->name.'/ru/admin_'.$module->name; ?>            
            <?php } else { ?>
            	<?php $link = $module->module_link; ?>           
            <?php } ?>
     
        <?php $groupe = $module->groupe_name; ?> 
        
        <div class="clear"><!--x--></div>
        <h3><b><?php echo $groupe ?></b></h3>   
        
        <?php //echo $module->groupe_name; ?>
        <div class="admin_panel_block">
            
            	 <a href="<?php echo $link ?>" title="<?php echo $module->title ?>">
                	<img src="<?php echo '/img/admin/modules/'.$module->name.'.png' ?>" alt=""/>
                </a><br/>
                <a href="<?php echo $link ?>" title="<?php echo $module->title ?>"><?php echo $module->title; ?></a>
            
        </div>
    <?php } else {?>
    	<?php if ($module->module_link == null) { ?>
            	<?php $link = '/'.$module->name.'/ru/admin_'.$module->name; ?>            
            <?php } else { ?>
            	<?php $link = $module->module_link; ?>           
            <?php } ?>
    
        <?php //TODO: сделать формирование ссылок тернарным оператором ?>
         <div class="admin_panel_block">
            
            	 <a href="<?php echo $link ?>" title="<?php echo $module->title ?>">
                	<img src="<?php echo '/img/admin/modules/'.$module->name.'.png' ?>" alt=""/>
                </a><br/>
                <a href="<?php echo $link ?>" title="<?php echo $module->title ?>"><?php echo $module->title; ?></a>
            
        </div>
    <?php }?>
     
<?php } ?>
</div>
</div>

<div id="right_block">

      <div class="block_r blue">
        <h3><b>Дополнительно</b></h3>
			<p>Краткая справочная информация</p>
        
      </div>
    </div>
