<div class="cont_inner">
    <h1><?=$this->layout()->page->title?></h1>
    <? if (count($this->portfolio)) { ?>
        <div class="cont_inner portfolio">
            <div class="portf_menu">
                <span class="count_work">Всего работ: <b><?php echo $this->portfolio_count ?></b></span>
                <span class="god">
                    <a href="/portfoliolist/" <?php echo $cl = $this->year == 'all' ? 'class="active"' : '' ?>>Все</a> |
                    <?php for ($i = 0; $i < count($this->years); $i++) { ?>
                        <a href="/portfoliolist/year/<?php echo $this->years[$i] ?>" <?php echo $cl = $this->year == $this->years[$i] ? 'class="active"' : '' ?>><?php echo $this->years[$i] ?></a> |
                    <?php } ?>
                </span>
            </div>
            <div class="work_list overflow">
                <? foreach ($this->portfolio as $portfolio) { ?>
                    <div class="item">
                        <div class="bg">
                            <div class="photo">
                                <a href="/portfolioitem/item/<?= $portfolio['url'] ?>"><img src="/pics/portfolio/thumbs/<?php echo $portfolio['image'] ?>" alt="<?= $portfolio['title'] ?>" /></a>
                            </div>
                            <a class="title_work" href="/portfolioitem/item/<?= $portfolio['url'] ?>">
                                <?= $portfolio['title'] ?>
                            </a>
                        </div>
                    </div>
                <? } ?>
            </div>
        </div>
    <? } ?>
</div>


