<?if(count($this->portfolio)) {?>
<div class="cont_inner portfolio">
    <div class="portf_menu">
  <span class="count_work">Всего работ: <b><?php echo count($this->portfolio) ?></b></span>
  <span class="god">
      <a href="/portfoliolist/" <?php echo $cl = $this->year == 'all'? 'class="active"': '' ?>>Все</a> |
  <?php for($i=0; $i<count($this->years); $i++) { ?>    
      <a href="/portfoliolist/year/<?php echo $this->years[$i] ?>" <?php echo $cl = $this->year == $this->years[$i]? 'class="active"': '' ?>><?php echo $this->years[$i] ?></a> |
  <?php } ?>    
  </span>    
  </div>
   <div class="work_list overflow"> 
        <?foreach($this->portfolio as $portfolio) {?>
   <div class="item">
     <div class="bg">
       <div class="photo">
           <a href="/portfoliolist/item/<?=$portfolio['id']?>"><img src="/pics/portfolio/<?php echo $portfolio['small_img'] ?>" alt="" width="100" height="90" /></a>
       </div>
         <?=$portfolio['name'] ?>
     </div>
   </div>    
   
    
   
  <?}?>
</div> 
</div><?}?>



