<div id="left_block"  class="form_page">
				
							
							
							
							<form method="post" id="edit_form" action="<?=$this->currentModule?>/edit/<?=$this->item->id ? 'id/'.$this->item->id.'/' : ''?><?=$this->peoples_id ? 'peoples_id/'.$this->peoples_id.'/' : ''?>" enctype="multipart/form-data"  >
							<?if ($this->ok==1) {?>
								<p align="center"><font color="green"><b>Данные сохранены</b></font></p>
							<?} ?>							
							<?if ($this->err==1) {?>
								<p align="center"><font color="red"><b>Заполните поля помеченные звездочкой</b></font></p>
							<?} ?>	
							
							<div class="content_block">
						        <p class="form_name">system_name</p>								
								<?=$this->formText('edit[system_name]', $this->item->system_name) ?>
								
						        <p class="form_name">title <span class="ser_text size11">(используется в структуре разделов)</span><p>
								<?=$this->formText('edit[title]', $this->item->title) ?>
								
								<p class="form_name">module</p>								
								<?=$this->formSelect('edit[module]', $this->item->module, null, $this->modules) ?>
								
								<p class="form_name">controller_frontend</p>								
								<?=$this->formText('edit[controller_frontend]', $this->item->controller_frontend) ?>
								
								<p class="form_name">action_frontend</p>								
								<?=$this->formText('edit[action_frontend]', $this->item->action_frontend) ?>
								
								<p class="form_name">controller_backend</p>								
								<?=$this->formText('edit[controller_backend]', $this->item->controller_backend) ?>
								
								
								<p class="form_name">action_backend</p>								
								<?=$this->formText('edit[action_backend]', $this->item->action_backend) ?>
								
								<p class="form_name">priority</p>								
								<?=$this->formText('edit[priority]', $this->item->priority) ?>
								
								<p class="form_name">Active</p>								
								<?=$this->formCheckbox('edit[active]', null, array('class'=>'checkbox', 'checked'=>$this->item->active)) ?> Yes
								
								<p class="form_name">Переход в модуль из структуры</p>								
								<?=$this->formCheckbox('edit[go_to_module]', null, array('class'=>'checkbox', 'checked'=>$this->item->go_to_module)) ?> Yes
								
								<input type="hidden" name="id" value="<?=$this->item->id ?>">	
						      </div>
						      <div class="right">
						        <button class="orange" type="button" onclick="location.href='<?=$this->currentModule?>'"><span><em>Отменить</em></span></button>
						        <button  type="submit"><span><em>Сохранить</em></span></button>
						      </div>
														
													
														
							</form>
</div>
<div id="right_block">
      <div class="block_r gray">
        <h3><b>Действия</b></h3>
        <ul>
          <li><a href="<?=$this->currentModule?>/edit/">Создать элемент</a></li>
          <li><a href="<?=$this->currentModule?>">Вернутся к списку</a></li>
        </ul>        
      </div>      
  </div>							
							