<div id="left_block">
	<div class="prava_dostupa">
	<table id="news_table" cellspacing="0" cellpadding="0" border="0">
								<tr class="head">
									<th>Название</th>
									<th>Операции</th>
								</tr>
								<?php
                                                                foreach($this->all as $key => $data)
                                                                    {?>
                                                                      <tr>
																		<td  width="200">
                                                                            <a href = '<?=$this->currentModule?>/edit/mod/<?=$data->name?>' title="Добавить тип раздела"><img src="/img/admin/add.png" alt="" /></a>
                                                                            &nbsp;<strong><?=$data->title?></strong>
                                                                        </td>
                                                                        <td >
                                                                        	<?php 
                                                                        	
                                                                        	/**
                                                                        	 * TODO вынести вызов класса в контроллер
                                                                        	 */
                                                                        	?>
                                                                           <?php $divisions = SiteDivisionsType::getInstance()->getdivisions($data->name);?>
                                                                            <?php if ($divisions->count()){?>
                                                                            	<table class="divisions_list">
                                                                            	<?php foreach ($divisions as $division){?>
                                                                            		<tr id="row_<?php echo $division->id?>">
				                                                                      <td class="division" id="elem_<?php echo $division->id?>">
				                                                                          -- <strong><a  href ="<?=$this->currentModule?>/edit/id/<?=$division->id?>/" title="редактировать"><?=$division->title?></a></strong>
				                                                                      </td>
				                                                                      <td  class="division" width="70">	                                                                      
					                                                                      <a href = '<?=$this->currentModule?>/edit/id/<?=$division->id?>' title="Изменить"><img src="/img/admin/edit.png" alt="" /></a>
					                                                                      <a href ="#" title="Включить/Выключить" id="active_<?php echo $division->id?>" onclick="return false;"><img src="/img/admin/active_<?=$division->active ?>.png" alt="" /></a>
					                                                                      <?php echo $this->ajaxStatusLink(array(
															                            		'target_id'	=>'active_'.$division->id,
															                            		'link_id'	=>'active_'.$division->id,
															                            		'target_url'=>$this->currentModule.'/changeactive',
															                            		'url_data'	=>"{id: ".$division->id."}",
															                            		'loader_img'=>"/img/loader.gif"
															                            		
															                            	));?>
					                                                                      <a href ="#" id="del_<?php echo $division->id?>" title="Удалить"><img src="/img/admin/delete.png" alt=""  /></a>
					                                                                      <?php echo $this->ajaxDeleteLink(array(
															                            		'target_id'	=>'elem_'.$division->id,
															                            		'delete_id'	=>'row_'.$division->id,
															                            		'link_id'	=>'del_'.$division->id,
															                            		'target_url'=>$this->currentModule.'/delete',
															                            		'url_data'	=>"{id: ".$division->id."}",
															                            		'loader_img'=>"/img/loader.gif"
															                            		
															                            	));?>
							                                                                      </td>
				                                                                      </tr>
                                                                            	<?php }?>
                                                                            	</table>
                                                                            <?php }?>
                                                                            
                                                                        </td>
                                                                      </tr>

                                                                         

                                                                    <?php }?>

								</table>
		</div>
							
</div>

  <div id="right_block">
      <div class="block_r gray">
        <h3><b>Действия</b></h3>
        <ul>
          <li><a href="<?=$this->currentModule?>/edit/">Создать элемент</a></li>
        </ul>
      </div>
  </div>



