<!--Top content-->
<div class="top_content">
    <!--Icons-->
    <div class="icons"><a href="/" title="На главную"><img src="/img/ico_home.gif" alt="на главную"  /></a> <a href="/sitemap" title="Карта сайта"><img src="/img/ico_sitemap.gif" alt="карта сайта" /></a> <a href="/contacts" title="Контакты"><img src="/img/ico_mail.gif" alt="" /></a> <!-- <a href="/cart"><img src="/img/ico_cart.gif" alt="" /></a> --></div>
    <!--End icons-->
    <?=$this->UserArea();?>
    <div class="info_block">
        <div class="head"><img src="/img/text_eda_zakaz.png" alt="Еда на заказ" /></div>
        <div class="text">
            Выберите блюда или <a href="#">составьте</a> их из наших инргедиентов. Мы доставим заказ к Вам домой или в офис в удобное для Вас время</div>
        <div class="contact">
            <p>с 10 до 24 часов ежедневно</p>
            <p class="phone">233-00-00, 657-00-00</p>

        </div>
        <div class="constructor"><a href="/dishmake">Наш конструктор</a></div>
    </div>
    <div class="constructor_link"><a href="/dishmake">sdfsdf</a></div>

</div>
<!--End top content-->