<div class="cont_inner news">
    <h1><?= $this->layout()->page->title ?></h1>

    <?php echo $this->layout()->page->content ?>

    <div class="clear"></div>
    <div class="form">
        <h3>Форма обратной связи</h3>

        <?php if ($this->send_success): ?>
            <ul>
                <li><b>Спасибо, Ваше сообщение отправлено.</b></li>
            </ul>
        <?php endif; ?>

        <?php if (isset($this->errors)): ?>
            <?php print $this->errors; ?>
        <?php endif; ?>

        <?php echo $this->form ?>

    </div>
</div>
