<div id="left_block"  class="form_page">
				
							
							
							
							<form method="post" id="edit_form" action="<?=$this->currentModule?>/edit/<?=$this->item->id ? 'id/'.$this->item->id.'/' : ''?><?=$this->peoples_id ? 'peoples_id/'.$this->peoples_id.'/' : ''?>" enctype="multipart/form-data"  >
							<?if ($this->ok==1) {?>
								<p align="center"><font color="green"><b>Данные сохранены</b></font></p>
							<?} ?>							
							<?if ($this->err==1) {?>
								<p align="center"><font color="red"><b>Заполните поля помеченные звездочкой</b></font></p>
							<?} ?>	
							
							<div class="content_block">
						       	<p class="form_name">Системное имя* <span class="ser_text size11">(используется для выборки блока из базы)</span><p>
								<?=$this->formText('edit[system_name]', $this->item->system_name, array('readonly'=>1)) ?>							
						        <p class="form_name">Название*<p>
						        <?=$this->formText('edit[title]', $this->item->title) ?>
								
								<p class="form_name">Контент<p>
								<?if ($this->item->type=='html'){?>
										<?	$this->fck_content->Value = $this->item->content;		
											$this->fck_content->Create();	
										?>
								
								<?} else {?>
									<?=$this->formTextarea('edit[content]', $this->item->content, array('rows'=>6))?>
									
								<?} ?>
							
								<p class="form_name">Приоритет<p>
						        <?=$this->formText('edit[priority]', $this->item->priority) ?>
								<p class="form_name">Активность <span class="ser_text size11">(На сайте отображаются только активные элементы)</span></p>								
								<?=$this->formCheckbox('edit[active]', null, array('class'=>'checkbox', 'checked'=>$this->item->active)) ?> Да
								
								<input type="hidden" name="id" value="<?=$this->item->id ?>">	
						      </div>
						      
						      <div class="right">
						        <button class="orange" type="button" onclick="location.href='<?=$this->currentModule?>'"><span><em>Отменить</em></span></button>
						        <button  type="submit"><span><em>Сохранить</em></span></button>
						      </div>
														
													
														
							</form>
</div>
<div id="right_block">
      <div class="block_r gray">
        <h3><b>Действия</b></h3>
        <ul>
          <li><a href="<?=$this->currentModule?>/add/">Создать элемент</a></li>
          <li><a href="<?=$this->currentModule?>">Вернутся к списку</a></li>
        </ul>        
      </div>      
  </div>							
							