<div id="left_block"  class="form_page">						
        <form method="post" id="edit_form" action="<?=$this->currentModule?>/edit/poll_id/<?=$this->parent_id?>/id/<?=$this->item->id?>" enctype="multipart/form-data"  >
        <?if ($this->ok==1) {?>
                <p align="center"><font color="green"><b>Данные сохранены</b></font></p>
        <?} ?>
        <?if ($this->err==1) {?>
                <p align="center"><font color="red"><b>Заполните поля помеченные звездочкой</b></font></p>
        <?} ?>

        <div class="content_block">

                <p class="form_name">Вопрос* <span class="ser_text size11">(текст вопроса)</span></p>
                <?=$this->formText('edit[title]', $this->item->title) ?>
                <p class="form_name">Приоритет* <span class="ser_text size11">(приоритет вопроса)</span></p>
                <?=$this->formText('edit[priority]', $this->item->priority) ?>
                <p class="form_name">Активность <span class="ser_text size11">(На сайте отображаются только активные элементы)</span></p>
                <?=$this->formCheckbox('edit[active]', null, array('class'=>'checkbox', 'checked'=>$this->item->active)) ?> Да


                <input type="hidden" name="id" value="<?=$this->item->id ?>">
      </div>
      <div class="right">
        <button class="orange" type="button" onclick="location.href='<?=$this->currentModule?>/index/poll_id/<?=$this->parent_id?>'"><span><em>Отменить</em></span></button>
        <button  type="submit"><span><em>Сохранить</em></span></button>
      </div>



        </form>
</div>
<div id="right_block">
      <div class="block_r gray">
        <h3><b>Действия</b></h3>
        <ul>
          <li><a href="<?=$this->currentModule?>/edit/poll_id/<?=$this->item->id?>">Создать опрос</a></li>
          <li><a href="<?=$this->currentModule?>">Вернутся к списку опросов</a></li>
          <li><a href = '<?=$this->currentModule?>items/index/poll_id/<?=$this->item->id?>'>Просмотреть список ответов</a></li>
        </ul>
      </div>      
  </div>							
							