<?if(isset($this->hits)) {?>
<div class="text_cont news_cont">
	<form action="/<?php echo $this->layout()->page->path?>" method="get">
	<input type="text" name="keywords" value="<?=$this->layout()->search?>">
	<input type="submit" value="Искать">
	</form>
    <p>по запросу "<?=$this->layout()->search?>" найдено результатов <?php echo $this->total?></p>
        <?foreach($this->hits as $hit) {?>
    <div class="news_item overflow">
        <div class="text_news overflow">
            <a href="/<?=$hit->url?>" class="head_news"><?=$hit->title?></a><br>
                    <?=(strlen($hit->original_content) > 330)?substr($hit->original_content, 0, strpos($hit->original_content,' ', 330)).'...':$hit->original_content;?>
            <div class="read_more"><a href="/<?=$hit->url?>">Подробнее</a></div>
        </div>
    </div>
            <?}?>
        <?=$this->pagination('/'.$this->layout()->page->path.'/keywords/'.$this->layout()->search.'/', (int)$this->total, (int)$this->onpage, $this->current_page); ?>
</div>
    <?}else{?>
        <div class="text_cont news_cont">
        	<form action="/<?php echo $this->layout()->page->path?>" method="get">
			<input type="text" name="keywords" value="<?=$this->layout()->search?>">
			<input type="submit" value="Искать">
			</form>
            <p>по запросу "<?=$this->layout()->search?>" ничего не найдено.</p>
        </div>
    <?}?>
    
    
    <?php echo $this->paginationControl($this->paginator, null, null, array('url_params'=>$this->url_params))?>