<?php

$this->parent_name = "<a href='/admin/' class='blue'>ГЛАВНАЯ СТРАНИЦА</a>" . 
        "\<a href='$this->currentModule' class='blue'>$this->caption</a>";
//$this->child_name = "Редактировать Элемент ";
$this->name = "Редактировать Элемент";
?>


<div class="description_page">
    <h2><?if ($this->item->id) {
            echo 'Редактировать';
        } else echo 'Добавить';?></h2>
</div>

<div class="content">
    <div id="left_block" class="form_page">
        <?php if ($this->error) { ?>
        <span style="color:red; margin-left: 16px"><strong><?=$this->error?></strong></span>
            <?php } ?>
        <form class="user_form" id="editform" method="post" action="<?=$this->currentModule?>/edit/<?=$this->item->id ? 'id/'.$this->item->id.'/' : ''?><?=$this->id_page ? 'id_page/'.$this->id_page.'/' : ''?>" enctype="multipart/form-data"  >
            <?if ($this->ok==1) {?>
            <p align="center"><font color="green"><b>Данные сохранены</b></font></p>
                <?} ?>
            <?if ($this->err==1) {?>
            <p align="center"><font color="red"><b>Заполните поля помеченные звездочкой</b></font></p>
                <?} ?>
            <?$item = $this->item; ?>
            <div class="content_block">
            	 <p class="form_name">Системное имя</p>
                <p>
                    <?=$this->formText('edit[system_name]', $item->system_name, array('class'=>'text', 'readonly'=>1)) ?>
                </p>
                <p class="form_name">Название</p>
                <p>
                    <?=$this->formText('edit[name]', $item->name, array('class'=>'text')) ?>
                </p>
            </div>
            <div class="content_block">
                <h3><span id="show-"><img alt="" src="images/admin/ico_show-.png"/></span> Контент</h3>
                <p class="form_name">Контент</p>
                <p>
                    <?if ($this->item->content!='')$this->content->Value =$this->item->content?>
                    <?php $this->content->Create();	?>
                </p>
                <p class="info_block">Поля, обязательные для шаблона:
                <p><?=$this->item->fields?></p>
                </p>
            </div>
            <input style="display: none;" "type="hidden" name="id" value="<?=$this->item->id ?>">
                   <input style="display: none;" name="edit[id_page]" value="<?=$this->id_page ?>">
            <div class="right">
                <button onclick="location.href='<?=$this->currentModule ?>'; return false;" class="orange"><span><em>Отменить</em></span></button>
                <button onclick="getElementById('editform').submit()"><span><em>Сохранить</em></span></button>
            </div>
        </form>
    </div>
    <div id="right_block">
        <div class="block_r gray">
            <h3><b>Действия</b></h3>
            <ul>
                <li><a href="<?=$this->currentModule?>/<?=$this->id_page ? 'index/id_page/'.$this->id_page.'/' : ''?>"><?=$this->caption;?></a></li>
                <li><?if ($this->item->id) {
                        echo 'Редактировать';
                    } else echo 'Добавить';?></li>
            </ul>
        </div>
    </div>
</div>
<br class="clear"/>