<?php
$this->parent_name = "<a href='/admin/' class='blue'>ГЛАВНАЯ СТРАНИЦА</a>" . 
        "\<a href='$this->currentModule/' class='blue'>$this->caption</a>";
//$this->child_name = $this->caption;
$this->name = $this->child_name;
?>
<div id="news_main_head">
    <div class="news_head">
        <div class="left_y"><!-- --></div>
        <div class="news_headbg_longer"><!-- --></div>
        <div class="right_y"><!-- --></div>
    </div>
    <div class="clear"><!-- --></div>
    <div class="content">
        <div class="prava_dostupa">
            <div class="clear"><!-- --></div>
            <div class="description_page">
                <h2><?=$this->caption?></h2>
            </div>
            <div id="left_block">
                <table style="margin-top: 0px;" width="100%" border="0" cellspacing="0" cellpadding="0">
                    <tr>
                        <th>Название</th>
                        <th>Операции</th>
                    </tr>
                    <?php
                    foreach ($this->all as $key => $data) {
                        ?>
                    <tr>
                        <td class="le_config">
                                 <a href = '<?=$this->currentModule?>/edit/id/<?=$data->id?>/<?=$this->id_page ? 'id_page/'.$this->id_page.'/' : '' ?>'><strong><?=$data->name ?></strong></a>

                        </td>
                        <td class="options">
                            <!-- <a href = '<?=$this->currentModule?>/activate/id/<?=$data->id?>/<?=$this->id_page ? 'id_page/'.$this->id_page.'/' : '' ?>'><img src="/img/admin/active_<?=$data->active ?>.gif" /></a> -->
                            <a href = '<?=$this->currentModule?>/edit/id/<?=$data->id?>/<?=$this->id_page ? 'id_page/'.$this->id_page.'/' : '' ?>'><img src="/img/admin/redact.gif" /></a>
                            <a href = '<?=$this->currentModule?>/delete/id/<?=$data->id?>/<?=$this->id_page ? 'id_page/'.$this->id_page.'/' : '' ?>'><img src="/img/admin/delete.gif"></a>
                        </td>
                    </tr>
                        <?php
                    }
                    ?>
                </table>
                <div style="padding-left: 20px;padding-top: 10px;" >
                    <?$peoples = $this->id_page ? 'id_page/'.$this->id_page.'/' : ''?>
                    <?=$this->Pagination($this->currentModule.'/index/'.$peoples, (int)$this->total, (int)$this->onpage, $this->current_page); ?>
                </div>
            </div>
            <div id="right_block">
                <div class="block_r gray">
                    <h3><b>Действия</b></h3>
                    <ul>
                        <li><?=$this->caption ?></li>
                        <li><a href="<?=$this->currentModule?>/add/<?=$this->id_page ? 'id_page/'.$this->id_page.'/' : ''?>">Добавить</a></li>
                    </ul>
                </div>
            </div>
        </div>
    </div>
    <div class="clear"><!-- --></div>
    <div class="redactor_footer">
        <div class="left_y"><!-- --></div>
        <div class="redactor_footerbg_longer">

        </div>
        <div class="right_y"><!-- --></div>
    </div>
</div>

