

<div class="content">
    <div id="left_block" class="form_page">
        <?php if ($this->error) { ?>
        <span style="color:red; margin-left: 16px"><strong><?=$this->error?></strong></span>
            <?php } ?>
        <form class="user_form" id="editform" method="post" action="<?=$this->currentModule?>/add/id_product/<?=$this->id_product?>/<?=$this->item->id ? 'id/'.$this->item->id.'/' : ''?>" enctype="multipart/form-data"  >
            <?if ($this->ok==1) {?>
            <p align="center"><font color="green"><b>Данные сохранены</b></font></p>
                <?} ?>
            <?if ($this->err==1) {?>
            <p align="center"><font color="red"><b>Заполните поля помеченные звездочкой</b></font></p>
                <?} ?>
            <?$item = $this->item; ?>
            <div class="content_block">
                <p class="form_name">Название</p>
                <p>                   
                    <?=$this->formSelect('id_option', null,null, $this->options)?>
                </p>
                <p class="form_name">Приоритет</p>
                <p>
                    <?=$this->formText('priority', $item->priority, array('style'=>'width:100px;')) ?>
                </p>
                <p class="form_name">Приоритет на сайте</p>
                <p>
                    <?=$this->formText('priority_site', $item->priority_site, array('style'=>'width:100px;')) ?>
                </p>
               
            </div>
           
                  
            <div class="right">
                <button onclick="location.href='<?=$this->currentModule ?>/index/id_product/<?=$this->id_product?>'; return false;" class="orange"><span><em>Отменить</em></span></button>
                <button onclick="getElementById('editform').submit()"><span><em>Сохранить</em></span></button>
            </div>
        </form>
    </div>
    <div id="right_block">
        <div class="block_r gray">
            <h3><b>Действия</b></h3>
            <ul>
                <li><a href="/catalog/<?=$this->lang?>/admin_product/edit/id/<?=$this->id_product?>">Фотографии</a></li>
                <li><?if ($this->item->id) {
                        echo 'Редактировать';
                    } else echo 'Добавить';?></li>
            </ul>
        </div>
    </div>
</div>
<br class="clear"/>