<script type="text/javascript" src="/js/translit.js"></script>
<div class="content">
    <div id="left_block" class="form_page">
        <?php if ($this->error) { ?>
        <span style="color:red; margin-left: 16px"><strong><?=$this->error?></strong></span>
            <?php } ?>
        <form class="user_form" id="editform" method="post" action="" enctype="multipart/form-data">
            <?if ($this->ok==1) {?>
            <p align="center"><font color="green"><b>Данные сохранены</b></font></p>
                <?} ?>
            <?if ($this->err==1) {?>
            <p align="center"><font color="red"><b>Заполните поля помеченные звездочкой</b></font></p>
                <?} ?>
            <?$item = $this->item; ?>
            <div class="content_block">
                <p class="form_name">Название</p>
                <p>
                    <?=$this->formText('edit[title]', $item['title'], array('class'=>'text')) ?>
                </p>
                <p class="form_name">Приоритет</p>
                <p>
                    <?=$this->formText('edit[priority]', $item['priority'], array('class'=>'text')) ?>
                </p>
            </div>

            <div class="content_block">
                <p class="form_name">Активность</p>
                <p>
                    <?=$this->formCheckbox('edit[active]', null, array('checked'=>$item['active']), array(1,0)) ?>
                </p>
            </div>

            <input style="display: none;" name="edit[id_page]" value="<?=$this->id_page ?>">
            <div class="right">
                <button onclick="location.href='<?=$this->currentModule ?>'; return false;" class="orange"><span><em>Отменить</em></span></button>
                <button onclick="getElementById('editform').submit()"><span><em>Сохранить</em></span></button>
            </div>
        </form>
    </div>
    <div id="right_block">
        <div class="block_r gray">
            <h3><b>Действия</b></h3>
            <ul>
                <li><a href="<?=$this->currentModule?>/index/id_page/<?=$this->id_page?>">Список элементов</a></li>
                <li><a href="<?=$this->currentModule?>/edit/id_page/<?=$this->id_page?>">Добавить</a></li>
            </ul>
        </div>
    </div>
</div>
<br class="clear"/>