




<div id="company_main_head">    
    <div class="clear"><!-- --></div>
    <div id="content">

        <div class="clear"><!-- --></div>
        <div id="left_block">
            <div class="prava_dostupa">
                <table  border="0" cellspacing="0" cellpadding="0">
                    <tr class="head">
                        <th>
                            <b>Описание</b>
                        </th>
                        <th>
                            <b>Дата, тип</b>
                        </th>
                        <th >
                            <b>Операции:</b>
                        </th>
                    </tr>

                    <? foreach($this->otzivy as $item) {?>
                    <tr id="row_<?php echo $item['id']?>">                            
                        <td id="elem_<?php echo $item['id']?>">
                        	<div style="padding-bottom: 10px;">
	                            <strong><?php echo $item->name?></strong>
	                            <strong><?php echo $item->email?></strong>
                           
                            </div>
                            <div style="padding-left: 5px;">
                            <?php echo $item->content ?>
                            </div>
                            
                        </td>
                        <td>
                        	<?php echo $item->date?><br/>
                        	<strong><?php echo $this->prin_types[$item->prizn]?></strong>
                        </td>
                        <td class="options">
                        <a href="#" id="active_<?php echo $item['id']?>" onclick="return false;" title="Изменить активность"><img src="/img/admin/active_<?=$item['is_active']?>.png" /></a>&nbsp;
                            	<?php echo $this->ajaxStatusLink(array(
                            		'target_id'	=>'active_'.$item['id'],
                            		'link_id'	=>'active_'.$item['id'],
                            		'target_url'=>$this->url(array()).'/changeactive',
                            		'url_data'	=>"{id: ".$item['id']."}",
                            		'loader_img'=>"/img/loader.gif"
                            		
                            	));?>
                            	
                            	
                            	
                            	
                                <a href="#" onclick="return false;" title="Отображать на главной" id="main_<?php echo $item['id']?>"><img src="/img/admin/main_<?=$item['is_main']?>.gif" /></a>&nbsp;
                                	<?php echo $this->ajaxStatusLink(array(
                            		'target_id'	=>'main_'.$item['id'],
                            		'link_id'	=>'main_'.$item['id'],
                            		'target_url'=>$this->url(array()).'/changemain',
                            		'url_data'	=>"{id: ".$item['id']."}",
                            		'loader_img'=>"/img/loader.gif"
                            		
                            	));?>
                            	
                                 <a href="#" id="del_<?php echo $item['id']?>" title="Удалить" onclick="return false;"><img src="/img/admin/delete.png"></a>
                                    	<?php echo $this->ajaxDeleteLink(array(
		                            		'target_id'	=>'elem_'.$item['id'],
		                            		'delete_id'	=>'row_'.$item['id'],
		                            		'link_id'	=>'del_'.$item['id'],
		                            		'target_url'=>$this->url(array()).'/delete',
		                            		'url_data'	=>"{id: ".$item['id']."}",
		                            		'loader_img'=>"/img/loader.gif"
		                            		
		                            	));?>
                        
                        </td>
                        
                                    </tr>
                                        <?}?>

                                    </table>
                                    </div>
                                    <div>Всего <?php echo $this->paginator->getTotalItemCount() ?></div>
									<?php if ($this->paginator->count()>1){?>
										<?php echo $this->paginator?>
									<?php }?>
                                    
                                    <!-- / Навигация по страницам -->
                                    </div>
                                    <div id="right_block">
                                        <div class="block_r gray">
                                            <h3><b>Действия</b></h3>                                           
                                            <ul>
                                                <li <?php echo is_null($this->prizn) ? 'class="active"' : ''?>>
                                                	<a href="<?php echo $this->url(array('prizn'=>null))?>">Смотреть все</a>
                                                </li>
                                                <li <?php echo (!is_null($this->prizn) && $this->prizn!=1 ) ? 'class="active"' : ''?>>
                                                	<a href="<?php echo $this->url(array('prizn'=>0))?>">Отзывы</a>
                                                </li>
                                                <li <?php $this->prizn==1 ? 'class="active"' : ''?>>
                                                	<a href="<?php echo $this->url(array('prizn'=>1))?>">Предложения</a>
                                                </li>
                                                
                                            </ul>
                                        </div>
                                    </div>
                                    </div>

                                    </div>