
<div class="top_menu">
    <ul>
        <?foreach ($this->menu as $key => $data) { ?>
            <?php $item = $data['item'];?>
            <li>
                <a href="/<?=$item->id!=844 ? $item->path : '' ?>" title="<?=$item->title?>" <?=$item->id==$this->current ? 'class="active"' : ''?>>
                    <span><?=$item->title?></span>
                   
                </a>
                <?php if (isset($data['childs']) && count($data['childs'])){ ?>
                	 
                	<ul>
                		<?php foreach ($data['childs'] as $child){?>
                			<li>
                				<a href="/<?=$child->path?>" title="<?=$child->title?>" <?=$child->id==$this->current ? 'class="active"' : ''?>>
				                    <span><?=$child->title?></span>
				                </a>
                			</li>
                		
                		<?php }?>
                		
                	</ul>
                <?php }?>
            </li>
        <?}?>
    </ul>
</div>



