<script>
    var delid;
    var pageid

    function go(id,page){

        delid=id;
        pageid = page;

        var sure = confirm("Вы действительно хотите удалить страницу?");
        if (sure) {
            window.location = "<?=$this->currentModule?>/delete/id/"+delid+"/id_page/"+"<?=$this->id_page?>";
            alert("Страница удалена");
        }
    }
</script>


<div id="company_main_head">    
    <div class="clear"><!-- --></div>
    <div id="content">

        <div class="clear"><!-- --></div>
        <div id="left_block">

            <div class="constructor">
                <form id="constr_prices_form" method="post" action="" enctype="multipart/form-data">
                <table class="ctable" style="margin-top: 0px; width: 750;" border="0" cellspacing="0" cellpadding="0">
                    <tr class="head">
                        <th style="width:200px;">
                            <b>Группа ингредиентов</b>
                        </th>
                        <th style="width:200px;">
                            <b>Ингредиенты</b>
                        </th>
                        <th>
                            <b>Размеры и цены</b>
                        </th>
                    </tr>
                    <tr>
                        <td></td>
                        <td></td>
                        <td>
                            <table class="stable">
                               <tr>
                                   <?foreach($this->sizes as $size) {?>
                                        <td class="w150px"><?=$size['title']?></td>
                                    <?}?>
                               </tr>
                           </table>
                        </td>
                    </tr>
                    <tr align="left">  
                        <td class="vtop">
                            <ul>
                            <? foreach($this->groups as $group) {?>
                                <li class="constr_type" type_id="<?=$group['id']?>">
                                    <span class="pad_left_5"><?=$group['title']?></span>

                                </li>
                            <?}?>
                            </ul>
                        </td>
                        <td class="vtop">
                            <ul>
                            <? foreach($this->groups as $group) {?>
                                <li class="constr_group" id="cogr_<?=$group['id']?>">
                                    <ul >
                                        <?foreach($group['items'] as $item){?>
                                        <li class="constr_group_item" group_id="<?=$item['id']?>">
                                            <span class="pad_left_5"><?=$item['title']?></span>
                                        </li>
                                        <?}?>
                                    </ul>
                                </li>
                            <?}?>
                            </ul>
                        </td>
                        <td class="vtop">                           
                           
                            <?foreach($this->groups as $group) {?>
                               <table id="grss_<?=$group['id']?>" class="constr_group_size_set stable">
                                    <?foreach($group['items'] as $item){?>
                                        <tr>
                                            <?foreach($item['sizes'] as $size){?>
                                                <td class="const_input_td">
                                                    <?=$this->formText("prices[".$item['id']."][".$size['id']."]", $size['price'], array('class'=>'input text')) ?>
                                                </td>
                                            <?}?>
                                        </tr>
                                    <?}?>
                               </table>
                            <?}?>
                            
                           
                        </td>
                    </tr>
                </table>
                <div class="right">
                    <button onclick="location.href='/constructor/ru/admin_types/'; return false;" class="orange"><span><em>Отменить</em></span></button>
                    <button onclick="getElementById('constr_prices_form').submit()"><span><em>Сохранить</em></span></button>
                </div>
                </form>
            </div>
            <!-- / Навигация по страницам -->
        </div>
        <div id="right_block">
            <div class="block_r gray">
                <h3><b>Действия</b></h3>
                <ul>
                    <li class="active"><a href="/constructor/ru/admin_types/">Типы блюд</a></li>
                    <li><a href="<?=$this->currentModule?>/edit/type_id/<?=$this->type_id?>/">Добавить</a></li>
                </ul>
            </div>
        </div>
    </div>

</div>


<script type="text/javascript">
    $(document).ready(function() {

        $(".constr_group").hide();
        $(".constr_group_size_set").hide();

        $(".constr_type").click(function(){
            $(".constr_group").hide();
            var type_id = $(this).attr('type_id');
            $("#cogr_"+type_id).show();
            $(".constr_type").removeClass('active');
            $(this).toggleClass('active');
            $(".constr_group_size_set").hide();
            $("#grss_"+type_id).show();
        });

        $(".constr_group_item3").click(function(){
            $(".constr_group_size_set").hide();
            var group_id = $(this).attr('group_id');
            $("#grss_"+group_id).show();
            $(".constr_group_item").removeClass('active');
            $(this).toggleClass('active');
        });
        
    });
</script>


