<?if(count($this->item)) {?>
<div class="cont_inner news">
    <div class="item">    	
        <b class="date"><i><?php echo $this->item->date?></i></b>
        <h3><?=$this->item->name?></h3>
        <?if($this->item->big_img!=''){?>
            <div class="photo">
            	<img src="/pics/articles/big_img/<?php echo $this->item->big_img?>" alt="<?php echo $this->item->name?>" />
            </div>
        <?}?>
        	
            <?php echo $this->item->content?>
        
    </div>

</div>
<?}?>