<script type="text/javascript" src="/js/jquery/ui.core.js"></script>
<script type="text/javascript" src="/js/jquery/ui.datepicker.js"></script>
<script type="text/javascript" charset="utf-8">
    $(function()
    {
        $("#datepicker").datepicker({ dateFormat: 'dd.mm.yy' });
    });
</script>

<div class="content">
    <div id="left_block" class="form_page">
        <?if ($this->ok==1) { ?>
        <div class="content_block">
            <p class="data_saved">Данные сохранены</p>
        </div>
        <?} ?>
    
    	<?php echo $this->form?>
        
    </div>
    <div id="right_block">
        <div class="block_r gray">
            <h3><b>Действия</b></h3>
            <ul>
                <li><a href="<?=$this->currentModul?>/index/id_page/<?=$this->id_page?>">Список элементов</a></li>                
            </ul>
        </div>
    </div>
</div>