

<script type="text/javascript" src="/js/translit.js"></script>



<div class="content">
    <div id="left_block" class="form_page">
       <?php echo $this->form?>
    </div>
    <div id="right_block">
        <div class="block_r gray">
            <h3><b>Действия</b></h3>
            <ul>
                <li><a href="<?=$this->currentModul?>/index">Список элементов</a></li>               
                <li><a href="<?=$this->currentModul?>/edit">Добавить</a></li>
            </ul>
        </div>
    </div>
</div>
<br class="clear"/>