<div class="clear"></div>	
<div class="form">
	<h3>Форма обратной связи</h3>
	<form action="<?= $this->escape( $this->element->getAction() ); ?>" 
		method="<?= $this->escape( $this->element->getMethod() ); ?>" >
		
		<div class="bg">
			<div class="item">
				<label for="<?php echo $this->element->name->getId()?>">
					<?php echo $this->element->name->getLabel(); ?>
				</label>
				<?php echo $this->element->name; ?>
				
				
			
			</div>
			
			<div class="item">
				<label for="<?php echo $this->element->email->getId()?>">
					<?php echo $this->element->email->getLabel(); ?>
				</label>
				<?php echo $this->element->email; ?>
			
			</div>
			
			<div class="item">
				<label for="<?php echo $this->element->prizn->getId()?>">
					<?php echo $this->element->prizn->getLabel(); ?>
				</label>
				<?php echo $this->element->prizn; ?>
				<div class="clear"></div>	
			</div>
			
			<div class="item">
				<label for="<?php echo $this->element->content->getId()?>">
					<?php echo $this->element->content->getLabel(); ?>
				</label>
				<?php echo $this->element->content; ?>
			
			</div>
		</div>
		<div class="capcha">
			<label for="<?php echo $this->element->captcha->getId()?>">
				<?php echo $this->element->captcha->getLabel(); ?>
			</label>
			<div class="overflow">
				<?php echo $this->element->captcha; ?>			 			
				<?php echo $this->element->submit; ?>
				<div class="clear"></div>
			</div>
		</div>
		
		
		
		
		
	
	</form>
</div>	
