<?if(count($this->otzivy)) {?>
<div class="portfolio_types">
Смотреть: 
<a href="<?php echo $this->url(array(), null, true)?>" <?php echo is_null($this->prizn) ? 'class="active"' : ''?>>Все</a>&nbsp;|&nbsp; 
<a href="<?php echo $this->url(array('prizn'=>1))?>" <?php echo $this->prizn==1 ? 'class="active"' : ''?>>Предложения</a>&nbsp;|&nbsp; 
<a href="<?php echo $this->url(array('prizn'=>0))?>" <?php echo (!is_null($this->prizn) && $this->prizn!=1 ) ? 'class="active"' : ''?>>Отзывы</a>
</div>

<div class="cont_inner news">
        <?foreach($this->otzivy as $otziv) {?>
   <div class="item">
        <b class="date"><i><?php echo $otziv->date?></i></b>       
        <?php echo $otziv->name?>
        <br/>
        <?php echo $otziv->content?>
       
        
            
     </div>
   
  <?}?>
 
<?}?>
<?php if ($this->paginator->count() > 1) { ?>
    <?php echo $this->paginationControl($this->paginator, null, null, array('url_params'=>$this->url_params))?>
<?php } ?>


        <?if ($this->ok==1) { ?>
        <div class="content_block">
            <p class="data_saved"><font color="green"><strong>Спасибо!<br/>Ваше сообщение отправлено.</strong></font></p>
        </div>
        <?} ?>
      
     
<?=$this->form->render() ?> 	

</div>


