<div id="left_block"  class="form_page">
    <form method="post" id="edit_form" action="<?=$this->currentModule?>/edit/<?=$this->item->id ? 'id/'.$this->item->id.'/' : ''?><?=$this->peoples_id ? 'peoples_id/'.$this->peoples_id.'/' : ''?>" enctype="multipart/form-data"  >
        <?if ($this->ok==1) {?>
        <p align="center"><font color="green"><b>Данные сохранены</b></font></p>
            <?} ?>
        <?if ($this->err==1) {?>
        <p align="center"><font color="red"><b>Заполните поля помеченные звездочкой</b></font></p>
            <?} ?>

        <div class="content_block">
            <p class="form_name">Модуль</p>
            <?=$this->formText('edit[name]', $this->item->name, array('readonly'=>1)) ?>

            <p class="form_name">Заголовок <span class="ser_text size11">(используется в структуре разделов)</span><p>
                <?=$this->formText('edit[title]', $this->item->title) ?>
                
            <p class="form_name">Приоритет</p>
            <?=$this->formText('edit[priority]', $this->item->priority) ?>

            <p class="form_name">Активность</p>
            <?=$this->formcheckbox('edit[active]', null, array('class'=>'checkbox', 'checked'=>$this->item->active)) ?> Yes

            <input type="hidden" name="id" value="<?=$this->item->id ?>">
            <input type="hidden" name="name" value="<?=$this->item->name ?>">
        </div>
        <div class="right">
            <button class="orange" type="button" onclick="location.href='<?=$this->currentModule?>'"><span><em>Отменить</em></span></button>
            <button  type="submit"><span><em>Сохранить</em></span></button>
        </div>



    </form>
</div>
<div id="right_block">
    <div class="block_r gray">
        <h3><b>Действия</b></h3>
        <ul>
            <li><a href="<?=$this->currentModule?>/add/">Установить модуль</a></li>
            <li><a href="<?=$this->currentModule?>">Вернутся к списку</a></li>
        </ul>        
    </div>
</div>							
