<div id="left_block">
	<div class="prava_dostupa">
	<table id="news_table" cellspacing="0" cellpadding="0" border="0">
								<tr class="head">
									<th>Модуль</th>
									<th>Системное имя</th>
									<th>Описание</th>	
									<th>Операции</th>
																	
								</tr>
								<?php
									foreach ($this->items as $key => $data){
									 	$stl = $data->installed ? "style=\"color:green;\"" : "style=\"color:red;\"";
                                                                                $instlnk =  $data->installed ? "<a id=\"".$data['name']."\" href=\"#\" onclick=\"return false;\" title=\"Выключить модуль\"><img src=\"/img/admin/module_1.png\"></a>"
                                                                                                             : "<a id=\"".$data['name']."\" href=\"#\" onclick=\"return false;\" title=\"Включить модуль\"><img src=\"/img/admin/module_0.png\"></a>"	?>
                                                                                <?php $visible = $data['visible'] ? 'Не показывать в админке' : 'Показывать в админке'?>
											<tr id="row_<?php echo $data['id'] ?>">														
												
												<td class="main" <?php echo $stl ?>>
													<?=$data['title'] ?>
												</td>
                                                                        <td class="main" >
                                                                            <strong>
													<?php echo $data['name']?>
                                                                            </strong>                          
												</td>
												<td class="main" >
													<?=$data['describe'] ?>
												</td>										
												<td class="options">
													
                                                                                                <?php echo $instlnk ?>       
                                                                                                
                                                                                                    <a href="#" id="visible_<?php echo $data['id']?>" onclick="return false;" title="Отображать в админке"><img src="/img/admin/visible_<?php echo $data['visible']?>.png" alt="<?php echo $visible?>"></a>
                                                                                                         <?php echo $this->ajaxStatusLink(array(
                                                                                                                                        'target_id'	=>'visible_'.$data['id'],
                                                                                                                                        'link_id'	=>'visible_'.$data['id'],
                                                                                                                                        'target_url'=>  $this->url(array()).'/visibility',
                                                                                                                                        'url_data'	=>"{id: ".$data['id'].",visible: '".$data['visible']."'}",
                                                                                                                                        'loader_img'=>"/img/loader.gif"

                                                                                                                                ));?>
                                                                                                        
												</td>
                                                                                                <?php echo $this->ajaxStatusLink(array(
                                                                                                                                        'target_id'	=>'row_'.$data['id'],
                                                                                                                                        'link_id'	=>$data['name'],
                                                                                                                                        'target_url'=> $this->url(array()).'/install',
                                                                                                                                        'url_data'	=>"{installed: ".$data['installed'].",module_name: '".$data['name']."'}",
                                                                                                                                        'loader_img'=>"/img/horizontal_loader.gif"

                                                                                                                                ));?> 
											</tr>
                                                                                        
										<?php
									}
								?>
							</table>
		</div>					
							
</div>

 


				
