
<?if(count($this->item)) {?>
<div class="cont_inner news">
    <div class="item">
        <b class="date"><i><?=  date('d.m.Y',strtotime($this->item->created_at));?></i></b>
        <h3><?php print $this->item->name ?></h3>
        <?if($this->item->big_img){?>
            <div class="photo"><img src="/thumb.php?img=/pics/news/<?=$this->item->big_img?>&w=130&h=115" alt="" /></div>
        <?}?>
        
            <?=$this->item->content?>
        
    </div>

</div>
<?}?>