<div id="left_block"  class="form_page">
				
							
							
							
							<form method="post" id="edit_form" action="<?=$this->currentModule?>/edit/<?=$this->item->id ? 'id/'.$this->item->id.'/' : ''?>" enctype="multipart/form-data"  >
							<?if ($this->ok==1) {?>
								<p align="center"><font color="green"><b>Данные сохранены</b></font></p>
							<?} ?>							
							<?if ($this->ok===0) {?>
								<p align="center"><font color="red"><b>Заполните поля помеченные звездочкой</b></font></p>
							<?} ?>	
							
							<div class="content_block">
						       	<p class="form_name">Название*</p>
						        <?=$this->formText('title', $this->item->title) ?>
						        
						       	<p class="form_name">System name* <span class="ser_text size11">(название латиницей, используется для выборки товаров по этому полю)</span></p>
						        <?=$this->formText('system_name', $this->item->system_name) ?>
						        
						       	<p class="form_name">Тип*</p>
						        <?=$this->formSelect('form_type', $this->item->form_type, null, $this->types) ?>
						        
						        <p class="form_name">Значение по умолчанию</p>
						        <?=$this->formText('default_value', $this->item->default_value) ?>
						        
						   
						   	
								<p class="form_name">Приоритет</p>
						        <?=$this->formText('priority', (int)$this->item->priority, array('style'=>'width: 200px;')) ?>
								<p class="form_name">Активность <span class="ser_text size11">(На сайте отображаются только активные элементы)</span></p>								
								<?=$this->formCheckbox('active', null, array('class'=>'checkbox', 'checked'=>$this->item->active)) ?> Да
								<?php if ($this->item->id){?>
									<input type="hidden" name="id" value="<?=$this->item->id ?>">
								<?php }?>	
						      </div>
						      
						      <div class="right">
						        <button class="orange" type="button" onclick="location.href='<?=$this->currentModule?>'"><span><em>Отменить</em></span></button>
						        <button  type="submit"><span><em>Сохранить</em></span></button>
						      </div>
														
													
														
							</form>
</div>
<div id="right_block">
      <div class="block_r gray">
        <h3><b>Действия</b></h3>
        <ul>
          <li><a href="<?=$this->currentModule?>/edit/">Создать элемент</a></li>
        
          <li><a href="<?=$this->currentModule?>">Вернутся к списку</a></li>
           <li><a href="/catalog/<?=$this->layout()->lang?>/admin_division/">Вернутсья к дереву разделов</a></li>
        </ul>        
      </div>

    <?if (isset($this->params) && count($this->params)){?>
    <div class="block_r gray">
        <h3><b>Опции</b></h3>
        <ul class="admin_option_ul">
            <?foreach ($this->params as $param){?>
                <li class="admin_product_options_li">
                    <span class="list_arrow">
                        <a href="/catalog/ru/admin_product_options_values/index/id_product/<?=$this->item->id?>/id_option/<?=$param['id_option']?>">
                        <?=$param['title']?>
                       </a>
                    </span>
                    <?if (isset($param['values']) && count($param['values'])){?>
                        <ul class="admin_option_ul">
                            <?foreach ($param['values'] as $value){?>
                                <li class="admin_product_options_li">
                                    <span class="list_arrow">
                                        <a href="/catalog/ru/admin_product_options_values/edit/id_product/<?=$this->item->id?>/id_option/<?=$param['id']?>/id/<?=$value['id']?>">
                                        <?=$value['title']?>
                                        </a>
                                        &nbsp;&nbsp;&nbsp;(<?=$value['price']?> бр)
                                    </span>
                                </li>
                            <?}?>
                        </ul>
                    <?}?>
                    </li>
            <?}?>
        </ul>
    </div>
    <?}?>
  </div>							
							